# fly.toml app configuration file generated for rahul-rangarao on 2026-08-31T09:35:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rahul-rangarao'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

  [[http_service.checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/app/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
